services:
  - type: web
    name: mark-graphics
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip
      pip3 install Pillow
      npm install
    startCommand: node server.js
    plan: free
